config/routes.rb
AirbnbClone::Application.routes.draw do
  root :to => "listings#index"
  devise_for :users
  resources :users, :only => [:show]
  resources :listings do
    resources :listing_photos
  end
  resources :listing_photos

  resources :charges
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user
  has_many :listing_photos
  accepts_nested_attributes_for :listing_photos

  before_save :capitalize_all

  def capitalize_all
    self.title = self.title.titleize
    self.city.capitalize!
    self.state.capitalize!
    self.description.capitalize!
    self.address = self.address.titleize
  end

  def self.text_search(query)
    if query.present?
      where("title @@ :q or description @@ :q or state @@ :q or city @@ :q", q: query)
    else
      scoped
    end
  end
end

app/models/listing_photo.rb
class ListingPhoto < ActiveRecord::Base
  belongs_to :listing
  has_attached_file :photo, :styles => { :large => "450x450#", :medium => "300x300#", :thumb => "100x100#" },
                            # :convert_options => { :thumb => "-quality 75 -strip" },
                            :default_url => "/images/:style/missing.png"

  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  # validates_presense_of :photo

  before_save :capitalize_all

  def capitalize_all
    self.caption.capitalize!
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :listings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :medium => "300x300#", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :name
    devise_parameter_sanitizer.for(:account_update) << :address
    devise_parameter_sanitizer.for(:account_update) << :city
    devise_parameter_sanitizer.for(:account_update) << :state
    devise_parameter_sanitizer.for(:account_update) << :zipcode
    devise_parameter_sanitizer.for(:account_update) << :avatar
    # devise_parameter_sanitizer.for(:account_update) { |u| u.permit( :name, :address, :city, :state, :zipcode, :avatar) }
end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

def new
end

def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create(
    :email => 'example@stripe.com',
    :card  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to charges_path
end

end

app/controllers/listing_photos_controller.rb
class ListingPhotosController < ApplicationController

def new
  @listing_photo = ListingPhoto.new
  @listing = Listing.find(params[:listing_id])
 end

def create
  @listing_photo = ListingPhoto.new( listing_photo_params )
    if @listing_photo.save
      redirect_to listing_url(@listing_photo.listing_id)
    else
      render 'new'
    end
end

private

# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.

def listing_photo_params
  params.require(:listing_photo).permit(:photo, :caption, :listing_id)
end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  def index
    @listings = Listing.text_search(params[:query]).page(params[:page]).per_page(9)
  end

  def new
    @listing = Listing.new
    @listing.listing_photos.build
  end

  def create
    @listing = Listing.new(listing_params)
    if @listing.save
      redirect_to listings_url
    else
      render 'new'
    end
    # respond_to do |format|
    #   format.html { redirect_to listings_url }
    #   format.js
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    @listing.update_attributes!(listing_params)
    respond_to do |format|
      format.html { redirect_to listings_url }
      format.js
    end
  end

  def show
    @listing = Listing.find(params[:id])
    @posting_user = User.find(@listing.user_id)
  end

  def destroy
    @listing = Lising.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to listings_url }
      format.js
    end
  end

  private
  def listing_params
    params.require(:listing).permit( :title, :description, :address, :city, :state, :zipcode, :price, :user_id, :id, :listing_photos_attributes => [:id, :caption, :listing_id, :photo])
  end

  # def query_params
  #   params.require(:query).permit(:title, :description)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AirbnbClone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>

  <div class="container">
  <div class="navbar navbar-inverse navbar-embossed" role="navigation">
    <div class="navbar-header">
  <ul class="nav navbar-nav">
          <li> <a class="brand" href="/"> AirBNB </a></li>

        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">

            <%= form_tag listings_path, method: :get do %>

              <%= text_field_tag :query, params[:query], :class => "form-control", :placeholder => "Where are you going?" %>
          </div>
              <%= submit_tag "Search", name: nil, :class => "btn btn-info" %>

            <% end %>
        </form>




    <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li><%= link_to "New Listing", new_listing_path(:user_id => current_user.id) %> </li>
        </ul>
        <ul class="nav navbar-nav">
          <li><%= link_to 'Edit profile', edit_user_registration_path %> </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "btn btn-primary" %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <div class="navbar-text">
            <li><h7>Logged in as <%= current_user.email %></h7></li>
          </div>
        </ul>

    <% else %>
    <ul class="nav navbar-nav">
      <li><%= link_to "Sign up", new_user_registration_path %></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Login", new_user_session_path %></li>
    </ul>
    <% end %>
  </ul>
  </div>
</div>

<div class="jumbotron">
<%= yield %>
</div>
</div>
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/listing_photos/new.html.erb
<%= form_for @listing_photo, :html => { :multipart => true} do |f| %>
    <div class="form-group">
      <%= f.label :caption %></br>
      <%= f.text_field :caption %>
    </div>
    <div class="form-group">
    <%= f.file_field :photo %>
    </div>
    <div class="form-group">
    <%= f.hidden_field :listing_id, :value => @listing.id %></br>
     <%= f.submit(:class => "btn btn-primary") %>
    </div>
    <% end %>
</div>

app/views/listings/_form.html.erb
<div class="listing-form">
  <%= form_for @listing, :html => { :multipart => true } do |f| %>
    <div class="form-group">
      <%= f.label :title %></br>
      <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <%= f.label :description %></br>
      <%= f.text_field :description %>
    </div>
    <div class="form-group">
      <%= f.label :address %></br>
      <%= f.text_field :address %>
    </div>
     <div class="form-group">
      <%= f.label :city %></br>
      <%= f.text_field :city %>
    </div>
     <div class="form-group">
      <%= f.label :state %></br>
      <%= f.text_field :state %>
    </div>
     <div class="form-group">
      <%= f.label :zipcode %></br>
      <%= f.text_field :zipcode %>
    </div>
     <div class="form-group">
      <%= f.label :price  %></br>
      <%= f.text_field :price %>
    </div>
    <div class="form-group">
     <%= f.hidden_field :user_id, :value => current_user.id %></br>
   </div>
   <%= f.fields_for :listing_photos do |x| %>
     <div class="form-group">
        <%= x.label :caption %></br>
        <%= x.text_field :caption %>
      </div>
      <div class="form-group">
        <%= x.label :photo %></br>
        <%= x.file_field :photo %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.submit(:class => "btn btn-primary") %>
    </div>

  <% end %>
</div>

app/views/listings/_listing.html.erb
  <div class="col-xs-3 col-sm-3 col-md-4">
    <div class="thumbnail">
    <% if listing.listing_photos.first != nil %>
    <div class="thumbnail-image">
      <%= link_to image_tag(listing.listing_photos.first.photo), listing_path(listing) %>
    </div>
    <% end %>

        <h6 class="truncate"><%= link_to listing.title, listing_path(listing) %></h6>
        <p><%= link_to listing.city, listing_path(listing), :class => "black" %>, <%= link_to listing.state, listing_path(listing), :class => "black" %></p>
        <p><%= link_to "More Info", listing_path(listing), :class => "btn btn-xs btn-primary" %>
      </div>
  </div>

app/views/listings/create.js.erb
$('#new_listing').remove();
$('#new_link').show();
$('.listings').append('<%= j render(@listing) %>');

app/views/listings/index.html.erb
<% content_for(:title, "Listings | BonnieBNB") %>

 <div class="row">
  <ul class="thumbnails">
 <div class = "listings">

<%= render @listings %>

</div>
</ul>
</div>
<div class="pagination">
<%= will_paginate @listings %>
</div>

app/views/listings/new.html.erb
<%= content_for(:title, "New Listing") %>

<div class="main-page container">
  <div class="row">

    <h1>New Listing</h1>

    <%= render 'form' %>
  </div>
</div>

app/views/listings/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>')

app/views/listings/show.html.erb
<% content_for(:title, "Your Listing | BonnieBNB") %>
<h1><%= @listing.title %></h1>
<ul>
<% @listing.listing_photos.each do |listing_photo| %>
  <%= image_tag listing_photo.photo(:large) %>
 <% end %>
 </ul>
<p>Description: <%= @listing.description %></p>
<p>City: <%= @listing.city %></p>
<p>State: <%= @listing.state %></p>
<p>Price: <%= @listing.price %></p>



<h4> Host</h4>
<p> Name: <%= @posting_user.name %></p>
<p> <%= image_tag @posting_user.avatar.url(:thumb) %> </p>

<% if current_user.id == @listing.user_id %>

  <%= link_to "Add Pictures", new_listing_photo_path(:listing_id => @listing.id), :class => "btn btn-default" %>
<% end %>

<%= link_to "Back", listings_path, :class => "btn btn-primary" %>